spring:
   application:
      name: zipkin-server

server:
  port: ${PORT:9411}
  
  
management:
  metrics:
    web:
      server:
        auto-time-requests: false
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    registerWithEureka: true
    fetch-registry: true
#    registerWithEureka: true
  #  fetch-registry: true
            #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
            #defaultZone: http://host.docker.internal:8761/eureka,http://host.docker.internal:8762/eureka
            #http://192.168.10.1:8761/eureka,http://192.168.10.10:8762/eureka
  #management.metrics.web.server.auto-time-requests=false
#eureka:
  #client:
       # serviceUrl:
        #    defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
            #defaultZone: http://host.docker.internal:8761/eureka,http://host.docker.internal:8762/eureka
            