spring:
   application:
      name: MoviesAPI
   rabbitmq:
     host: localhost
     #host: 192.168.10.1
     port: 5672
     username: guest
     password: guest

server:
  port: ${PORT:8765}
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
            #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
            #defaultZone: http://host.docker.internal:8761/eureka,http://host.docker.internal:8762/eureka
            
            
  instance:
    instance-id: Movies-1
    metadataMap:
      zone: zone1
      
  
endpoints:
   shutdown:
      enabled: true
      sensitive: false
   

management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"
        
        
zipkin:
   base-url: http://localhost:9411/
      #base-url: http://host.docker.internal:9411/
             
sleuth:
 sampler:
  percentage: 1.0
   