spring:
   application:
      name: SearchAPI2
     
server:
  port: ${PORT:8769}
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
            #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
            #defaultZone: http://host.docker.internal:8761/eureka,http://host.docker.internal:8762/eureka
            
  instance:
    metadataMap:
      zone: zone2


endpoints:
  shutdown:
    enabled: true
    sensitive: false
        
zipkin:
   base-url: http://localhost:9411/
      #base-url: http://host.docker.internal:9411/
      
sleuth:
 sampler:
  percentage: 1.0
   