spring:
   sleuth:
      web:
         skipPattern: (^cleanup.*|.+favicon.*)
   application:
      name: Zull

server:
  port: ${PORT:8764}
      
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
        registerWithEureka: true
        preferSameZoneEureka: false
    instance:
        metadataMap:
            zone: zone1,zone2
    
        
zuul:
   prefix: /route
   routes:
      Movies-Service:
        path: /MoviesAPI/**
        serviceId: MoviesAPI
        
        
      Comments-Service:
        path: /CommentsAPI/**
        serviceId: CommentsAPI
        
        
      Rating-Service:
        path: /RatingAPI/**
        serviceId: RatingAPI
        
        
      Search-Service:
        path: /SearchAPI/**
        serviceId: SearchAPI
        
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
ribbon:
    eureka:
        enabled: true
    ConnectTimeout: 30000
    ReadTimeout: 30000
    
    
zipkin:
   base-url: http://localhost:9411/
   #base-url: http://ZIPKIN-SERVER:9411/
      #base-url: http://host.docker.internal:9411/
      
sleuth:
   sampler:
      percentage: 1.0
   
   
   
   