spring:
  application:
    name: Service-Registry

eureka:
  instance:
    metadata-map:
      zone: zone1
    hostname: localhost
    #hostname: 192.168.10.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
      #defaultZone: http://localhost:8762/eureka/
server:
  port: ${PORT:8761}

  
zipkin:
   base-url: http://localhost:9411/
      #base-url: http://host.docker.internal:9411/
      
sleuth:
 sampler:
  percentage: 1.0