spring:
   application:
      name: discovery-service
   
     
server:
  port: ${PORT:8761}
   
eureka:
  instance:
    metadataMap:
        zone: zone1
  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
zipkin:
   base-url: http://localhost:9411/   
    
    