spring:
   application:
      name: discovery-service
   
     
server:
  port: ${PORT:8761}
   
eureka:
  instance:
    metadataMap:
        zone: zone1
  
  client:
    registerWithEureka: false
    fetchRegistry: false
    
zipkin:
   base-url: http://localhost:9411/   
    
    